// Mocks generated by Mockito 5.4.5 from annotations
// in youbloomdemo/test/unit_test/login_repo_test/login_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:youbloomdemo/data/network/network_api_services.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkApiServices extends _i1.Mock
    implements _i2.NetworkApiServices {
  @override
  _i3.Future<dynamic> getApi(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getApi, [url]),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> postApi(dynamic data, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#postApi, [data, url]),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  dynamic returnResponse(_i4.Response? response) => super.noSuchMethod(
    Invocation.method(#returnResponse, [response]),
    returnValueForMissingStub: null,
  );
}
